# Generated by Django 6.1.1 on 2026-09-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('runtime_minutes', models.PositiveIntegerField()),
                ('mpaa_rating', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='catalog.genre')),
            ],
            options={
                'ordering': ['title', 'release_year'],
            },
        ),
        migrations.CreateModel(
            name='MovieCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20)),
                ('acquired_date', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='catalog.movie')),
            ],
            options={
                'ordering': ['movie__title', 'copy_number'],
                'constraints': [models.UniqueConstraint(fields=('movie', 'copy_number'), name='unique_copy_number_per_movie')],
            },
        ),
    ]
